-- MySQL Script generated by MySQL Workbench
-- Sun Feb 23 14:40:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
/*DROP SCHEMA IF EXISTS `mydb` ;*/

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MAIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAIN` (
  `CartID` INT NOT NULL,
  `CartName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CartID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOGS` (
  `CartID` INT NOT NULL,
  `LOG` VARCHAR(45) NULL,
  `TIMESTAMP` DATETIME(6) NOT NULL,
  PRIMARY KEY (`CartID`, `TIMESTAMP`),
  CONSTRAINT `fk_LOGS_MAIN`
    FOREIGN KEY (`CartID`)
    REFERENCES `mydb`.`MAIN` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Menu_ItemID` INT NOT NULL,
  `ITEM` VARCHAR(45) NOT NULL,
  `PRICE` VARCHAR(45) NOT NULL,
  `DISCOUNT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Menu_ItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAIN_has_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAIN_has_Menu` (
  `MAIN_CartID` INT NOT NULL,
  `Menu_Menu_Item` INT NOT NULL,
  PRIMARY KEY (`MAIN_CartID`, `Menu_Menu_Item`),
  /*INDEX `fk_MAIN_has_Menu_Menu1_idx` (`Menu_Menu_Item` ASC) VISIBLE,
  INDEX `fk_MAIN_has_Menu_MAIN1_idx` (`MAIN_CartID` ASC) VISIBLE,*/
  CONSTRAINT `fk_MAIN_has_Menu_MAIN1`
    FOREIGN KEY (`MAIN_CartID`)
    REFERENCES `mydb`.`MAIN` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MAIN_has_Menu_Menu1`
    FOREIGN KEY (`Menu_Menu_Item`)
    REFERENCES `mydb`.`Menu` (`Menu_ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location_CUST` (
  `LocationId` INT NOT NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitude` VARCHAR(45) NOT NULL,
  `TIMSTAMP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDOR` (
  `CartID` INT NOT NULL,
  `LoginName` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CartID`),
  CONSTRAINT `fk_VENDOR_MAIN1`
    FOREIGN KEY (`CartID`)
    REFERENCES `mydb`.`MAIN` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN` (
  `AdminID` INT NOT NULL,
  `LoginName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAIN_has_ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAIN_has_ADMIN` (
  `MAIN_CartID` INT NOT NULL,
  `ADMIN_AdminID` INT NOT NULL,
  PRIMARY KEY (`MAIN_CartID`, `ADMIN_AdminID`),
 /*INDEX `fk_MAIN_has_ADMIN_ADMIN1_idx` (`ADMIN_AdminID` ASC) VISIBLE,
  INDEX `fk_MAIN_has_ADMIN_MAIN1_idx` (`MAIN_CartID` ASC) VISIBLE,*/
  CONSTRAINT `fk_MAIN_has_ADMIN_MAIN1`
    FOREIGN KEY (`MAIN_CartID`)
    REFERENCES `mydb`.`MAIN` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MAIN_has_ADMIN_ADMIN1`
    FOREIGN KEY (`ADMIN_AdminID`)
    REFERENCES `mydb`.`ADMIN` (`AdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CART` (
  `CartId` INT NOT NULL,
  `Menu_ItemID` INT NOT NULL,
  PRIMARY KEY (`CartId`),
  /* INDEX `fk_CART_Menu1_idx` (`Menu_ItemID` ASC) VISIBLE, */
  CONSTRAINT `fk_CART_Menu1`
    FOREIGN KEY (`Menu_ItemID`)
    REFERENCES `mydb`.`Menu` (`Menu_ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location_CART` (
  `LocationId` INT NOT NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitude` VARCHAR(45) NOT NULL,
  `TIMSTAMP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL,
  `LocationId` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `ProfiePicture` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`),
   /*INDEX `fk_Customer_Location1_idx` (`LocationId` ASC) VISIBLE,*/
  CONSTRAINT `fk_Customer_Location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDERS` (
  `OrderID` INT NOT NULL,
  `CartId` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
   /*`CustomerID` VARCHAR(45) NOT NULL,*/
  PRIMARY KEY (`OrderID`),
   /*INDEX `fk_ORDERS_CART1_idx` (`CartId` ASC) VISIBLE,
  INDEX `fk_ORDERS_Customer1_idx` (`CustomerID` ASC) VISIBLE,*/
  CONSTRAINT `fk_ORDERS_CART1`
    FOREIGN KEY (`CartId`)
    REFERENCES `mydb`.`CART` (`CartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAIN_has_ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAIN_has_ORDERS` (
  `MAIN_CartID` INT NOT NULL,
  `ORDERS_OrderID` INT NOT NULL,
  PRIMARY KEY (`MAIN_CartID`, `ORDERS_OrderID`),
   /*INDEX `fk_MAIN_has_ORDERS_ORDERS1_idx` (`ORDERS_OrderID` ASC) VISIBLE,
  INDEX `fk_MAIN_has_ORDERS_MAIN1_idx` (`MAIN_CartID` ASC) VISIBLE,*/
  CONSTRAINT `fk_MAIN_has_ORDERS_MAIN1`
    FOREIGN KEY (`MAIN_CartID`)
    REFERENCES `mydb`.`MAIN` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MAIN_has_ORDERS_ORDERS1`
    FOREIGN KEY (`ORDERS_OrderID`)
    REFERENCES `mydb`.`ORDERS` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
